version: '3.8'
services:
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: exam_db
      POSTGRES_PASSWORD: Qq654321
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: app
    build: ./
    environment:
      JAVA_OPTS: |-
        -Dspring.profiles.active=docker
        -Xmx3500m
        -Xms1500m
      SPRING_CONFIG_LOCATION: /usr/config/
    ports:
      - '8080:8080'