spring:
  application:
    name: exam
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/exam_db
    username: postgres
    password: Qq654321
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect